export const ATTEMPTING='ATTEMPTING'
export const AUTH_SUCCESS='AUTH_SUCCESS'
export const AUTH_FAILED='AUTH_FAILED'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const POST_LOADING='POST_LOADING';
export const POST_UPLOADED='POST_UPLOADED';
export const POST_FAILD='POST_FAILD';